feat: auth tokens
DFOnline/CodeClient pull request #89
Opened 2024-09-07 20:01 UTC by RedVortexDev

Adds authentication tokens so apps can keep their scopes when reconnecting.

`INC` is from the game to your app
`OUT` is from the app to your game
```
--- CONNECT TO ws://localhost:31375 ---
OUT token
IN wPLp47FI9on6f3Tklt4uu2ge66Vhl67c
OUT scopes read_plot
IN auth
---                  DISCONNECT                  ---
---                     CONNECT                     ---
OUT  wPLp47FI9on6f3Tklt4uu2ge66Vhl67c // the same token we got
IN auth
OUT scopes
IN read_plot // we keep our scopes!
```

2024-09-21 19:11 UTC, GeorgeRNG requested changes

2024-09-21 19:11 UTC, GeorgeRNG commented on src/main/java/dev/dfonline/codeclient/Utility.java
> +        Random random = new Random(System.currentTimeMillis());
if I'm going to ask for changes I might as well:
maybe `SecureRandom`?
for that matter if you do use secure random you could condense this function down to
```java
SecureRandom rand = new SecureRandom();
byte[] randomBytes = new byte[16]; // or longer
random.nextBytes(randomBytes);
return HexFormat.of().formatHex(randomBytes); // or something else for a wider charset
```
or maybe I'm just nitpicking.

2024-09-22 16:33 UTC, RedVortexDev commented
guh accidentally pushed devauth

2024-09-25 11:09 UTC, GeorgeRNG approved these changes

2024-09-25 13:35 UTC, merged