Add Destroy Item Reset
DFOnline/CodeClient pull request #93
Opened 2024-09-22 17:07 UTC by RedVortexDev

Original by recode, only works in the dev-space to not clash when using dev mode for building.

2024-09-23 08:20 UTC, GeorgeRNG requested changes

2024-09-23 20:25 UTC, RedVortexDev commented on src/main/java/dev/dfonline/codeclient/mixin/screen/MCreativeInventoryScreen.java
> +                CodeClient.MC.setScreen(null);
recode does close it, probably to prevent people spamming it and getting kicked by accident

2024-09-24 07:41 UTC, GeorgeRNG commented on src/main/java/dev/dfonline/codeclient/mixin/screen/MCreativeInventoryScreen.java
> +                CodeClient.MC.setScreen(null);
then it's fine to keep as is. I'll probably see if I can make something later to check if the inv is default

2024-09-24 07:47 UTC, GeorgeRNG approved these changes

2024-09-24 14:01 UTC, merged